apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: prime-ui
  namespace: default
spec:
  template:
    metadata:
      name: prime-ui-grpc
    spec:
      containers:
        - image: github.com/vagababov/prime-client
          args: ["--use_grpc", "--backend", "prime-grpc:80", "--host", "prime-grpc.default.35.222.221.17.xip.io"]
          ports:
            - name: http1
              containerPort: 8080
      containerConcurrency: 15
