apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: prime-ui
  namespace: default
spec:
  template:
    metadata:
      name: prime-ui-grpc
    spec:
      containers:
        - image: github.com/vagababov/prime-client
          args: ["--use_grpc", "--backend", "prime-grpc:80", "--host", "prime-grpc.default.35.222.221.17.xip.io"]
      containerConcurrency: 15
  traffic:
  - tag: http1 # Can't use http or grpc. Will collide with placeholder name.
    revisionName: prime-ui-http
    percent: 50
  - tag: grpc1
    revisionName: prime-ui-grpc
    percent: 50
  - tag: latest
    latestRevision: true
    percent: 0
